<a href="https://colab.research.google.com/github/hdhd7/MalashinLabs/blob/main/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Метод простых итераций
def iterations(matrix, b, max_iter=1000, tol=1e-6):
    matrix = np.array(matrix, dtype=float)
    b = np.array(b, dtype=float)
    n = len(matrix)
    x = np.zeros(n)  # начальные значения X

    for k in range(max_iter):
        x_new = np.copy(x)
        for i in range(n):
            s1 = sum(matrix[i][j] * x_new[j] for j in range(i))
            s2 = sum(matrix[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - s1 - s2) / matrix[i][i]

        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return (x_new, 0)  # достигнута необходимая точность
        x = x_new
    return (x, 1)  # не достигнута необходимая точность

# Метод решения системы уравнений с использованием матричного метода (метод Гаусса)
def solve(matrix, b):
    matrix = np.array(matrix, dtype=float)
    b = np.array(b, dtype=float)
    try:
        solutions = np.linalg.solve(matrix, b)
        return solutions
    except np.linalg.LinAlgError:
        return None

# Чтение данных из файла
matrix = []
b = []
with open('input_lab2.txt', 'r') as file:
    for line in file:
        row = [float(x) for x in line.split()]
        matrix.append(row[:-1])
        b.append(row[-1])

print("Матрица коэффициентов:")
print(np.array(matrix))
print("Вектор правых частей:")
print(np.array(b))

# Решение с помощью матричного метода
solutions = solve(matrix, b)
# Решение с помощью метода простых итераций
solutions2 = iterations(matrix, b)

print("Решения системы уравнений матричным методом:", solutions)
if solutions2[1] == 0:
    print("Решения при помощи метода простых итераций:", solutions2[0])
else:
    print("Метод простых итераций не сошёлся, полученные корни:", solutions2[0])

Матрица коэффициентов:
[[ 3.  5.  8.]
 [ 4.  7.  5.]
 [ 1.  9. 10.]]
Вектор правых частей:
[16. 16. 20.]
Решения системы уравнений матричным методом: [1. 1. 1.]
Решения при помощи метода простых итераций: [1.00000077 0.99999998 0.99999994]
